apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentournament.fullname" . }}
  namespace: {{ include "opentournament.namespace" . }}
  labels:
    {{- include "opentournament.labels" . | nindent 4 }}
data:
  games.yaml: |
    {{- toYaml .Values.catalog | nindent 4 }}
