{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opentournament.fullname" . }}
  namespace: {{ include "opentournament.namespace" . }}
  labels:
    {{- include "opentournament.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "opentournament.selectorLabels" . | nindent 6 }}
{{- end }}
