# touch .env
# docker volume create redis_data
# docker volume create postgres_data
# mkdir ./data/db_data ./data/redis_data
#
# docker compose up
# docker compose down

version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: opentournament-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      #- db_data:/var/lib/postgresql/data
      - "./data/db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7-alpine
    container_name: opentournament-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - "./data/redis_data:/data"
      #- redis_data:/data


  dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.4
    container_name: opentournament-dashboard
    restart: always
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
      - 4317:18889
    
#volumes:
#  db_data:
#    driver: local # Define the driver and options under the volume name
#    driver_opts:
#      type: none
#      device: "./data/db_data"
#      o: bind
#
#  redis_data:
#    driver: local
#    driver_opts:
#      type: none
#      device: "./data/redis_data"
#      o: bind
