global using Xunit;
global using Xunit.Abstractions;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using System.Net;
global using System.Text.Json;
global using System.Text;
global using Bogus;
global using Testcontainers.PostgreSql;
