// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (tournament_id, seq, type, data, private, recipients, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	TournamentID ids.TournamentID
	Seq          int64
	Type         string
	Data         json.RawMessage
	Private      json.RawMessage
	Recipients   []string
	CreatedAt    time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.TournamentID,
		arg.Seq,
		arg.Type,
		arg.Data,
		arg.Private,
		arg.Recipients,
		arg.CreatedAt,
	)
	return err
}

const lastEventSeq = `-- name: LastEventSeq :one
SELECT last_event_seq FROM tournaments WHERE id = $1
`

func (q *Queries) LastEventSeq(ctx context.Context, id ids.TournamentID) (int64, error) {
	row := q.db.QueryRow(ctx, lastEventSeq, id)
	var last_event_seq int64
	err := row.Scan(&last_event_seq)
	return last_event_seq, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT tournament_id, seq, type, data, private, recipients, created_at FROM events WHERE tournament_id = $1 AND seq > $2 ORDER BY seq LIMIT $3
`

type ListEventsAfterParams struct {
	TournamentID ids.TournamentID
	Seq          int64
	Limit        int32
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.TournamentID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.TournamentID,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.Private,
			&i.Recipients,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events WHERE created_at < $1
`

func (q *Queries) PruneEvents(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
