// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
)

const claimDueJobs = `-- name: ClaimDueJobs :many
UPDATE jobs SET due_at = $1, attempts = attempts + 1
WHERE id IN (
    SELECT id FROM jobs WHERE jobs.due_at <= $2
    ORDER BY jobs.due_at LIMIT $3 FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, tournament_id, match_id, due_at, attempts
`

type ClaimDueJobsParams struct {
	LeaseUntil time.Time
	Now        time.Time
	MaxJobs    int32
}

// Leases due jobs by pushing their due time forward, so a crashed worker's
// jobs become due again once the lease runs out.
func (q *Queries) ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, arg.LeaseUntil, arg.Now, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TournamentID,
			&i.MatchID,
			&i.DueAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishJob = `-- name: FinishJob :exec
DELETE FROM jobs WHERE id = $1 AND due_at = $2
`

type FinishJobParams struct {
	ID    int64
	DueAt time.Time
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob, arg.ID, arg.DueAt)
	return err
}

const nextJobDue = `-- name: NextJobDue :one
SELECT due_at FROM jobs ORDER BY due_at LIMIT 1
`

func (q *Queries) NextJobDue(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, nextJobDue)
	var due_at time.Time
	err := row.Scan(&due_at)
	return due_at, err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET due_at = $2 WHERE id = $1 AND due_at = $3
`

type RetryJobParams struct {
	ID          int64
	RetryAt     time.Time
	LeasedUntil time.Time
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.RetryAt, arg.LeasedUntil)
	return err
}

const scheduleJob = `-- name: ScheduleJob :exec
INSERT INTO jobs (kind, tournament_id, match_id, due_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, tournament_id, match_id) DO UPDATE SET due_at = EXCLUDED.due_at, attempts = 0
`

type ScheduleJobParams struct {
	Kind         string
	TournamentID ids.TournamentID
	MatchID      ids.MatchID
	DueAt        time.Time
}

func (q *Queries) ScheduleJob(ctx context.Context, arg ScheduleJobParams) error {
	_, err := q.db.Exec(ctx, scheduleJob,
		arg.Kind,
		arg.TournamentID,
		arg.MatchID,
		arg.DueAt,
	)
	return err
}

const unscheduleJob = `-- name: UnscheduleJob :exec
DELETE FROM jobs WHERE kind = $1 AND tournament_id = $2 AND match_id IS NOT DISTINCT FROM $3
`

type UnscheduleJobParams struct {
	Kind         string
	TournamentID ids.TournamentID
	MatchID      ids.MatchID
}

func (q *Queries) UnscheduleJob(ctx context.Context, arg UnscheduleJobParams) error {
	_, err := q.db.Exec(ctx, unscheduleJob, arg.Kind, arg.TournamentID, arg.MatchID)
	return err
}

const unscheduleTournamentJobs = `-- name: UnscheduleTournamentJobs :exec
DELETE FROM jobs WHERE tournament_id = $1
`

func (q *Queries) UnscheduleTournamentJobs(ctx context.Context, tournamentID ids.TournamentID) error {
	_, err := q.db.Exec(ctx, unscheduleTournamentJobs, tournamentID)
	return err
}
