// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
	"github.com/couchpartygames/opentournament/internal/lifecycle"
	"github.com/google/uuid"
)

const abortMatch = `-- name: AbortMatch :one
UPDATE matches SET status = 'allocating', aborts = aborts + 1, allocation_id = NULL,
                   server_name = NULL, server_address = NULL, server_port = NULL
WHERE id = $1 AND allocation_id = $2 AND server_name IS NOT NULL AND status IN ('allocating', 'in-progress')
RETURNING id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port
`

type AbortMatchParams struct {
	ID           ids.MatchID
	AllocationID ids.AllocationID
}

// Aborts a Match only if it still runs on the given allocation, so exactly
// one replica acts on a failed Game Server.
func (q *Queries) AbortMatch(ctx context.Context, arg AbortMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, abortMatch, arg.ID, arg.AllocationID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.StageID,
		&i.GroupID,
		&i.Key,
		&i.Round,
		&i.Bracket,
		&i.Status,
		&i.Result,
		&i.WinnerID,
		&i.ReadyAt,
		&i.ResultDeadline,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Aborts,
		&i.AllocationID,
		&i.ServerName,
		&i.ServerAddress,
		&i.ServerPort,
	)
	return i, err
}

const cancelOpenMatches = `-- name: CancelOpenMatches :many
UPDATE matches SET status = 'cancelled'
WHERE tournament_id = $1 AND status NOT IN ('completed', 'cancelled')
RETURNING id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port
`

func (q *Queries) CancelOpenMatches(ctx context.Context, tournamentID ids.TournamentID) ([]Match, error) {
	rows, err := q.db.Query(ctx, cancelOpenMatches, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAllocation = `-- name: ClearAllocation :exec
UPDATE matches SET allocation_id = NULL, server_name = NULL, server_address = NULL, server_port = NULL
WHERE id = $1 AND allocation_id = $2
`

type ClearAllocationParams struct {
	ID           ids.MatchID
	AllocationID ids.AllocationID
}

func (q *Queries) ClearAllocation(ctx context.Context, arg ClearAllocationParams) error {
	_, err := q.db.Exec(ctx, clearAllocation, arg.ID, arg.AllocationID)
	return err
}

const completeMatch = `-- name: CompleteMatch :exec
UPDATE matches SET status = 'completed', result = $2, winner_id = $3, completed_at = $4 WHERE id = $1
`

type CompleteMatchParams struct {
	ID          ids.MatchID
	Result      *lifecycle.MatchResult
	WinnerID    ids.ParticipantID
	CompletedAt *time.Time
}

func (q *Queries) CompleteMatch(ctx context.Context, arg CompleteMatchParams) error {
	_, err := q.db.Exec(ctx, completeMatch,
		arg.ID,
		arg.Result,
		arg.WinnerID,
		arg.CompletedAt,
	)
	return err
}

const confirmAllocation = `-- name: ConfirmAllocation :one
UPDATE matches SET server_name = $3, server_address = $4, server_port = $5
WHERE id = $1 AND allocation_id = $2 AND status = 'allocating' AND server_name IS NULL
RETURNING id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port
`

type ConfirmAllocationParams struct {
	ID            ids.MatchID
	AllocationID  ids.AllocationID
	ServerName    *string
	ServerAddress *string
	ServerPort    *int32
}

func (q *Queries) ConfirmAllocation(ctx context.Context, arg ConfirmAllocationParams) (Match, error) {
	row := q.db.QueryRow(ctx, confirmAllocation,
		arg.ID,
		arg.AllocationID,
		arg.ServerName,
		arg.ServerAddress,
		arg.ServerPort,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.StageID,
		&i.GroupID,
		&i.Key,
		&i.Round,
		&i.Bracket,
		&i.Status,
		&i.Result,
		&i.WinnerID,
		&i.ReadyAt,
		&i.ResultDeadline,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Aborts,
		&i.AllocationID,
		&i.ServerName,
		&i.ServerAddress,
		&i.ServerPort,
	)
	return i, err
}

const deleteSlots = `-- name: DeleteSlots :exec
DELETE FROM match_slots WHERE match_id = $1
`

func (q *Queries) DeleteSlots(ctx context.Context, matchID ids.MatchID) error {
	_, err := q.db.Exec(ctx, deleteSlots, matchID)
	return err
}

const getMatch = `-- name: GetMatch :one
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id ids.MatchID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.StageID,
		&i.GroupID,
		&i.Key,
		&i.Round,
		&i.Bracket,
		&i.Status,
		&i.Result,
		&i.WinnerID,
		&i.ReadyAt,
		&i.ResultDeadline,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Aborts,
		&i.AllocationID,
		&i.ServerName,
		&i.ServerAddress,
		&i.ServerPort,
	)
	return i, err
}

const insertBoutResult = `-- name: InsertBoutResult :exec
INSERT INTO bout_results (match_id, bout, participant_id, won, forfeited, placement, points, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBoutResultParams struct {
	MatchID       ids.MatchID
	Bout          int32
	ParticipantID ids.ParticipantID
	Won           bool
	Forfeited     bool
	Placement     *int32
	Points        *int32
	RecordedAt    time.Time
}

func (q *Queries) InsertBoutResult(ctx context.Context, arg InsertBoutResultParams) error {
	_, err := q.db.Exec(ctx, insertBoutResult,
		arg.MatchID,
		arg.Bout,
		arg.ParticipantID,
		arg.Won,
		arg.Forfeited,
		arg.Placement,
		arg.Points,
		arg.RecordedAt,
	)
	return err
}

const insertMatch = `-- name: InsertMatch :exec
INSERT INTO matches (id, tournament_id, stage_id, group_id, key, round, bracket, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
`

type InsertMatchParams struct {
	ID           ids.MatchID
	TournamentID ids.TournamentID
	StageID      ids.StageID
	GroupID      ids.GroupID
	Key          string
	Round        int32
	Bracket      string
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) error {
	_, err := q.db.Exec(ctx, insertMatch,
		arg.ID,
		arg.TournamentID,
		arg.StageID,
		arg.GroupID,
		arg.Key,
		arg.Round,
		arg.Bracket,
	)
	return err
}

const insertSlot = `-- name: InsertSlot :exec
INSERT INTO match_slots (match_id, slot, participant_id) VALUES ($1, $2, $3)
`

type InsertSlotParams struct {
	MatchID       ids.MatchID
	Slot          int32
	ParticipantID ids.ParticipantID
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) error {
	_, err := q.db.Exec(ctx, insertSlot, arg.MatchID, arg.Slot, arg.ParticipantID)
	return err
}

const listBoutsOfGroup = `-- name: ListBoutsOfGroup :many
SELECT b.match_id, b.bout, b.participant_id, b.won, b.forfeited, b.placement, b.points, b.recorded_at FROM bout_results b JOIN matches m ON m.id = b.match_id
WHERE m.group_id = $1 ORDER BY b.match_id, b.bout, b.participant_id
`

func (q *Queries) ListBoutsOfGroup(ctx context.Context, groupID ids.GroupID) ([]BoutResult, error) {
	rows, err := q.db.Query(ctx, listBoutsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoutResult{}
	for rows.Next() {
		var i BoutResult
		if err := rows.Scan(
			&i.MatchID,
			&i.Bout,
			&i.ParticipantID,
			&i.Won,
			&i.Forfeited,
			&i.Placement,
			&i.Points,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoutsOfMatch = `-- name: ListBoutsOfMatch :many
SELECT match_id, bout, participant_id, won, forfeited, placement, points, recorded_at FROM bout_results WHERE match_id = $1 ORDER BY bout, participant_id
`

func (q *Queries) ListBoutsOfMatch(ctx context.Context, matchID ids.MatchID) ([]BoutResult, error) {
	rows, err := q.db.Query(ctx, listBoutsOfMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoutResult{}
	for rows.Next() {
		var i BoutResult
		if err := rows.Scan(
			&i.MatchID,
			&i.Bout,
			&i.ParticipantID,
			&i.Won,
			&i.Forfeited,
			&i.Placement,
			&i.Points,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoutsOfTournament = `-- name: ListBoutsOfTournament :many
SELECT b.match_id, b.bout, b.participant_id, b.won, b.forfeited, b.placement, b.points, b.recorded_at FROM bout_results b JOIN matches m ON m.id = b.match_id
WHERE m.tournament_id = $1 ORDER BY b.match_id, b.bout, b.participant_id
`

func (q *Queries) ListBoutsOfTournament(ctx context.Context, tournamentID ids.TournamentID) ([]BoutResult, error) {
	rows, err := q.db.Query(ctx, listBoutsOfTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoutResult{}
	for rows.Next() {
		var i BoutResult
		if err := rows.Scan(
			&i.MatchID,
			&i.Bout,
			&i.ParticipantID,
			&i.Won,
			&i.Forfeited,
			&i.Placement,
			&i.Points,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByIds = `-- name: ListMatchesByIds :many
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListMatchesByIds(ctx context.Context, argIds []uuid.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByIds, argIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesOfGroup = `-- name: ListMatchesOfGroup :many
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches WHERE group_id = $1 ORDER BY round, key
`

func (q *Queries) ListMatchesOfGroup(ctx context.Context, groupID ids.GroupID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesOfTournament = `-- name: ListMatchesOfTournament :many
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches WHERE tournament_id = $1 ORDER BY stage_id, group_id, round, key
`

func (q *Queries) ListMatchesOfTournament(ctx context.Context, tournamentID ids.TournamentID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesOfTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesOnServers = `-- name: ListMatchesOnServers :many
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches WHERE status IN ('allocating', 'in-progress') AND server_name IS NOT NULL
`

func (q *Queries) ListMatchesOnServers(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesOnServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMatchesOfParticipant = `-- name: ListOpenMatchesOfParticipant :many
SELECT m.id, m.tournament_id, m.stage_id, m.group_id, m.key, m.round, m.bracket, m.status, m.result, m.winner_id, m.ready_at, m.result_deadline, m.started_at, m.completed_at, m.aborts, m.allocation_id, m.server_name, m.server_address, m.server_port FROM matches m JOIN match_slots s ON s.match_id = m.id
WHERE s.participant_id = $1 AND m.status IN ('ready', 'allocating', 'in-progress', 'stalled')
`

func (q *Queries) ListOpenMatchesOfParticipant(ctx context.Context, participantID ids.ParticipantID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listOpenMatchesOfParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMatchesOfTournament = `-- name: ListOpenMatchesOfTournament :many
SELECT id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port FROM matches
WHERE tournament_id = $1 AND status NOT IN ('completed', 'cancelled')
`

func (q *Queries) ListOpenMatchesOfTournament(ctx context.Context, tournamentID ids.TournamentID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listOpenMatchesOfTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.GroupID,
			&i.Key,
			&i.Round,
			&i.Bracket,
			&i.Status,
			&i.Result,
			&i.WinnerID,
			&i.ReadyAt,
			&i.ResultDeadline,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Aborts,
			&i.AllocationID,
			&i.ServerName,
			&i.ServerAddress,
			&i.ServerPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsOfGroup = `-- name: ListSlotsOfGroup :many
SELECT s.match_id, s.slot, s.participant_id FROM match_slots s JOIN matches m ON m.id = s.match_id
WHERE m.group_id = $1 ORDER BY s.match_id, s.slot
`

func (q *Queries) ListSlotsOfGroup(ctx context.Context, groupID ids.GroupID) ([]MatchSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchSlot{}
	for rows.Next() {
		var i MatchSlot
		if err := rows.Scan(&i.MatchID, &i.Slot, &i.ParticipantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsOfMatches = `-- name: ListSlotsOfMatches :many
SELECT match_id, slot, participant_id FROM match_slots WHERE match_id = ANY($1::uuid[]) ORDER BY match_id, slot
`

func (q *Queries) ListSlotsOfMatches(ctx context.Context, matchIds []uuid.UUID) ([]MatchSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsOfMatches, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchSlot{}
	for rows.Next() {
		var i MatchSlot
		if err := rows.Scan(&i.MatchID, &i.Slot, &i.ParticipantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsOfTournament = `-- name: ListSlotsOfTournament :many
SELECT s.match_id, s.slot, s.participant_id FROM match_slots s JOIN matches m ON m.id = s.match_id
WHERE m.tournament_id = $1 ORDER BY s.match_id, s.slot
`

func (q *Queries) ListSlotsOfTournament(ctx context.Context, tournamentID ids.TournamentID) ([]MatchSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsOfTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchSlot{}
	for rows.Next() {
		var i MatchSlot
		if err := rows.Scan(&i.MatchID, &i.Slot, &i.ParticipantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMatchStarted = `-- name: MarkMatchStarted :execrows
UPDATE matches SET status = 'in-progress', started_at = COALESCE(started_at, $3)
WHERE id = $1 AND allocation_id = $2 AND status IN ('allocating', 'in-progress')
`

type MarkMatchStartedParams struct {
	ID           ids.MatchID
	AllocationID ids.AllocationID
	StartedAt    *time.Time
}

func (q *Queries) MarkMatchStarted(ctx context.Context, arg MarkMatchStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMatchStarted, arg.ID, arg.AllocationID, arg.StartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestAllocation = `-- name: RequestAllocation :one
UPDATE matches SET status = 'allocating', allocation_id = $2,
                   server_name = NULL, server_address = NULL, server_port = NULL
WHERE id = $1 AND status IN ('ready', 'allocating') AND server_name IS NULL
RETURNING id, tournament_id, stage_id, group_id, key, round, bracket, status, result, winner_id, ready_at, result_deadline, started_at, completed_at, aborts, allocation_id, server_name, server_address, server_port
`

type RequestAllocationParams struct {
	ID           ids.MatchID
	AllocationID ids.AllocationID
}

// Starts an allocation attempt for a Match waiting for a Game Server.
func (q *Queries) RequestAllocation(ctx context.Context, arg RequestAllocationParams) (Match, error) {
	row := q.db.QueryRow(ctx, requestAllocation, arg.ID, arg.AllocationID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.StageID,
		&i.GroupID,
		&i.Key,
		&i.Round,
		&i.Bracket,
		&i.Status,
		&i.Result,
		&i.WinnerID,
		&i.ReadyAt,
		&i.ResultDeadline,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Aborts,
		&i.AllocationID,
		&i.ServerName,
		&i.ServerAddress,
		&i.ServerPort,
	)
	return i, err
}

const setMatchReady = `-- name: SetMatchReady :exec
UPDATE matches SET status = 'ready', ready_at = $2, result_deadline = $3 WHERE id = $1 AND status = 'pending'
`

type SetMatchReadyParams struct {
	ID             ids.MatchID
	ReadyAt        *time.Time
	ResultDeadline *time.Time
}

func (q *Queries) SetMatchReady(ctx context.Context, arg SetMatchReadyParams) error {
	_, err := q.db.Exec(ctx, setMatchReady, arg.ID, arg.ReadyAt, arg.ResultDeadline)
	return err
}

const setMatchStatus = `-- name: SetMatchStatus :exec
UPDATE matches SET status = $2 WHERE id = $1
`

type SetMatchStatusParams struct {
	ID     ids.MatchID
	Status lifecycle.MatchStatus
}

func (q *Queries) SetMatchStatus(ctx context.Context, arg SetMatchStatusParams) error {
	_, err := q.db.Exec(ctx, setMatchStatus, arg.ID, arg.Status)
	return err
}
