// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
	"github.com/couchpartygames/opentournament/internal/lifecycle"
)

type BoutResult struct {
	MatchID       ids.MatchID
	Bout          int32
	ParticipantID ids.ParticipantID
	Won           bool
	Forfeited     bool
	Placement     *int32
	Points        *int32
	RecordedAt    time.Time
}

type Event struct {
	TournamentID ids.TournamentID
	Seq          int64
	Type         string
	Data         json.RawMessage
	Private      json.RawMessage
	Recipients   []string
	CreatedAt    time.Time
}

type Group struct {
	ID           ids.GroupID
	TournamentID ids.TournamentID
	StageID      ids.StageID
	Position     int32
	Status       string
}

type GroupParticipant struct {
	GroupID       ids.GroupID
	ParticipantID ids.ParticipantID
	Seed          int32
	Lot           int32
	Advanced      bool
}

type Job struct {
	ID           int64
	Kind         string
	TournamentID ids.TournamentID
	MatchID      ids.MatchID
	DueAt        time.Time
	Attempts     int32
}

type Match struct {
	ID             ids.MatchID
	TournamentID   ids.TournamentID
	StageID        ids.StageID
	GroupID        ids.GroupID
	Key            string
	Round          int32
	Bracket        string
	Status         string
	Result         *string
	WinnerID       ids.ParticipantID
	ReadyAt        *time.Time
	ResultDeadline *time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
	Aborts         int32
	AllocationID   ids.AllocationID
	ServerName     *string
	ServerAddress  *string
	ServerPort     *int32
}

type MatchSlot struct {
	MatchID       ids.MatchID
	Slot          int32
	ParticipantID ids.ParticipantID
}

type Participant struct {
	ID            ids.ParticipantID
	TournamentID  ids.TournamentID
	IdentityKind  string
	IdentityValue string
	RegisteredBy  string
	Status        lifecycle.ParticipantStatus
	RegisteredAt  time.Time
	CheckedInAt   *time.Time
	FinalFrom     *int32
	FinalTo       *int32
}

type Stage struct {
	ID                    ids.StageID
	TournamentID          ids.TournamentID
	Position              int32
	Format                string
	GroupCount            int32
	Advancement           int32
	BestOf                int32
	Bouts                 int32
	SwissRounds           int32
	ResultDeadlineSeconds int32
	Status                string
}

type Tournament struct {
	ID                  ids.TournamentID
	GameID              string
	Name                string
	Organizer           string
	Status              lifecycle.TournamentStatus
	StartsAt            time.Time
	RegistrationOpensAt time.Time
	Capacity            int32
	MinimumParticipants int32
	CheckInEnabled      bool
	CheckInSeconds      int32
	LastEventSeq        int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CompletedAt         *time.Time
}
