// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package db

import (
	"context"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
	"github.com/couchpartygames/opentournament/internal/lifecycle"
	"github.com/google/uuid"
)

const activateParticipants = `-- name: ActivateParticipants :many
UPDATE participants SET status = 'active'
WHERE tournament_id = $1 AND status IN ('registered', 'checked-in')
RETURNING id
`

func (q *Queries) ActivateParticipants(ctx context.Context, tournamentID ids.TournamentID) ([]ids.ParticipantID, error) {
	rows, err := q.db.Query(ctx, activateParticipants, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ids.ParticipantID{}
	for rows.Next() {
		var id ids.ParticipantID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkInParticipant = `-- name: CheckInParticipant :exec
UPDATE participants SET status = 'checked-in', checked_in_at = $2 WHERE id = $1
`

type CheckInParticipantParams struct {
	ID          ids.ParticipantID
	CheckedInAt *time.Time
}

func (q *Queries) CheckInParticipant(ctx context.Context, arg CheckInParticipantParams) error {
	_, err := q.db.Exec(ctx, checkInParticipant, arg.ID, arg.CheckedInAt)
	return err
}

const countRegistered = `-- name: CountRegistered :one
SELECT count(*)::int FROM participants WHERE tournament_id = $1 AND status IN ('registered', 'checked-in')
`

func (q *Queries) CountRegistered(ctx context.Context, tournamentID ids.TournamentID) (int32, error) {
	row := q.db.QueryRow(ctx, countRegistered, tournamentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id ids.ParticipantID) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const dropNotCheckedIn = `-- name: DropNotCheckedIn :exec
UPDATE participants SET status = 'not-checked-in' WHERE tournament_id = $1 AND status = 'registered'
`

func (q *Queries) DropNotCheckedIn(ctx context.Context, tournamentID ids.TournamentID) error {
	_, err := q.db.Exec(ctx, dropNotCheckedIn, tournamentID)
	return err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, tournament_id, identity_kind, identity_value, registered_by, status, registered_at, checked_in_at, final_from, final_to FROM participants WHERE id = $1 AND tournament_id = $2
`

type GetParticipantParams struct {
	ID           ids.ParticipantID
	TournamentID ids.TournamentID
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.ID, arg.TournamentID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.IdentityKind,
		&i.IdentityValue,
		&i.RegisteredBy,
		&i.Status,
		&i.RegisteredAt,
		&i.CheckedInAt,
		&i.FinalFrom,
		&i.FinalTo,
	)
	return i, err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO participants (id, tournament_id, identity_kind, identity_value, registered_by, status,
                          registered_at, checked_in_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertParticipantParams struct {
	ID            ids.ParticipantID
	TournamentID  ids.TournamentID
	IdentityKind  string
	IdentityValue string
	RegisteredBy  string
	Status        lifecycle.ParticipantStatus
	RegisteredAt  time.Time
	CheckedInAt   *time.Time
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.Exec(ctx, insertParticipant,
		arg.ID,
		arg.TournamentID,
		arg.IdentityKind,
		arg.IdentityValue,
		arg.RegisteredBy,
		arg.Status,
		arg.RegisteredAt,
		arg.CheckedInAt,
	)
	return err
}

const listFinalPlacements = `-- name: ListFinalPlacements :many
SELECT id, tournament_id, identity_kind, identity_value, registered_by, status, registered_at, checked_in_at, final_from, final_to FROM participants
WHERE tournament_id = $1 AND final_from IS NOT NULL
ORDER BY final_from, final_to, id
`

func (q *Queries) ListFinalPlacements(ctx context.Context, tournamentID ids.TournamentID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listFinalPlacements, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.IdentityKind,
			&i.IdentityValue,
			&i.RegisteredBy,
			&i.Status,
			&i.RegisteredAt,
			&i.CheckedInAt,
			&i.FinalFrom,
			&i.FinalTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, tournament_id, identity_kind, identity_value, registered_by, status, registered_at, checked_in_at, final_from, final_to FROM participants WHERE tournament_id = $1 ORDER BY registered_at, id
`

func (q *Queries) ListParticipants(ctx context.Context, tournamentID ids.TournamentID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipants, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.IdentityKind,
			&i.IdentityValue,
			&i.RegisteredBy,
			&i.Status,
			&i.RegisteredAt,
			&i.CheckedInAt,
			&i.FinalFrom,
			&i.FinalTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByIds = `-- name: ListParticipantsByIds :many
SELECT id, tournament_id, identity_kind, identity_value, registered_by, status, registered_at, checked_in_at, final_from, final_to FROM participants WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListParticipantsByIds(ctx context.Context, argIds []uuid.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipantsByIds, argIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.IdentityKind,
			&i.IdentityValue,
			&i.RegisteredBy,
			&i.Status,
			&i.RegisteredAt,
			&i.CheckedInAt,
			&i.FinalFrom,
			&i.FinalTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFinalPlacement = `-- name: SetFinalPlacement :exec
UPDATE participants SET final_from = $2, final_to = $3 WHERE id = $1
`

type SetFinalPlacementParams struct {
	ID        ids.ParticipantID
	FinalFrom *int32
	FinalTo   *int32
}

func (q *Queries) SetFinalPlacement(ctx context.Context, arg SetFinalPlacementParams) error {
	_, err := q.db.Exec(ctx, setFinalPlacement, arg.ID, arg.FinalFrom, arg.FinalTo)
	return err
}

const setParticipantStatus = `-- name: SetParticipantStatus :exec
UPDATE participants SET status = $2 WHERE id = $1
`

type SetParticipantStatusParams struct {
	ID     ids.ParticipantID
	Status lifecycle.ParticipantStatus
}

func (q *Queries) SetParticipantStatus(ctx context.Context, arg SetParticipantStatusParams) error {
	_, err := q.db.Exec(ctx, setParticipantStatus, arg.ID, arg.Status)
	return err
}
