// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stages.sql

package db

import (
	"context"

	"github.com/couchpartygames/opentournament/internal/format"
	"github.com/couchpartygames/opentournament/internal/ids"
	"github.com/couchpartygames/opentournament/internal/lifecycle"
	"github.com/google/uuid"
)

const deleteStages = `-- name: DeleteStages :exec
DELETE FROM stages WHERE tournament_id = $1
`

func (q *Queries) DeleteStages(ctx context.Context, tournamentID ids.TournamentID) error {
	_, err := q.db.Exec(ctx, deleteStages, tournamentID)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, tournament_id, stage_id, position, status FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id ids.GroupID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.StageID,
		&i.Position,
		&i.Status,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, tournament_id, stage_id, position, status) VALUES ($1, $2, $3, $4, $5)
`

type InsertGroupParams struct {
	ID           ids.GroupID
	TournamentID ids.TournamentID
	StageID      ids.StageID
	Position     int32
	Status       lifecycle.StageStatus
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.TournamentID,
		arg.StageID,
		arg.Position,
		arg.Status,
	)
	return err
}

const insertGroupParticipant = `-- name: InsertGroupParticipant :exec
INSERT INTO group_participants (group_id, participant_id, seed, lot) VALUES ($1, $2, $3, $4)
`

type InsertGroupParticipantParams struct {
	GroupID       ids.GroupID
	ParticipantID ids.ParticipantID
	Seed          int32
	Lot           int32
}

func (q *Queries) InsertGroupParticipant(ctx context.Context, arg InsertGroupParticipantParams) error {
	_, err := q.db.Exec(ctx, insertGroupParticipant,
		arg.GroupID,
		arg.ParticipantID,
		arg.Seed,
		arg.Lot,
	)
	return err
}

const insertStage = `-- name: InsertStage :exec
INSERT INTO stages (id, tournament_id, position, format, group_count, advancement, best_of, bouts,
                    swiss_rounds, result_deadline_seconds, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertStageParams struct {
	ID                    ids.StageID
	TournamentID          ids.TournamentID
	Position              int32
	Format                format.Kind
	GroupCount            int32
	Advancement           int32
	BestOf                int32
	Bouts                 int32
	SwissRounds           int32
	ResultDeadlineSeconds int32
	Status                lifecycle.StageStatus
}

func (q *Queries) InsertStage(ctx context.Context, arg InsertStageParams) error {
	_, err := q.db.Exec(ctx, insertStage,
		arg.ID,
		arg.TournamentID,
		arg.Position,
		arg.Format,
		arg.GroupCount,
		arg.Advancement,
		arg.BestOf,
		arg.Bouts,
		arg.SwissRounds,
		arg.ResultDeadlineSeconds,
		arg.Status,
	)
	return err
}

const listGroupParticipants = `-- name: ListGroupParticipants :many
SELECT e.group_id, e.participant_id, e.seed, e.lot, e.advanced, p.status
FROM group_participants e JOIN participants p ON p.id = e.participant_id
WHERE e.group_id = $1
ORDER BY e.seed
`

type ListGroupParticipantsRow struct {
	GroupID       ids.GroupID
	ParticipantID ids.ParticipantID
	Seed          int32
	Lot           int32
	Advanced      bool
	Status        lifecycle.ParticipantStatus
}

func (q *Queries) ListGroupParticipants(ctx context.Context, groupID ids.GroupID) ([]ListGroupParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listGroupParticipants, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupParticipantsRow{}
	for rows.Next() {
		var i ListGroupParticipantsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ParticipantID,
			&i.Seed,
			&i.Lot,
			&i.Advanced,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupParticipantsOfTournament = `-- name: ListGroupParticipantsOfTournament :many
SELECT e.group_id, e.participant_id, e.seed, e.lot, e.advanced, p.status
FROM group_participants e
JOIN groups g ON g.id = e.group_id
JOIN participants p ON p.id = e.participant_id
WHERE g.tournament_id = $1
ORDER BY e.group_id, e.seed
`

type ListGroupParticipantsOfTournamentRow struct {
	GroupID       ids.GroupID
	ParticipantID ids.ParticipantID
	Seed          int32
	Lot           int32
	Advanced      bool
	Status        lifecycle.ParticipantStatus
}

func (q *Queries) ListGroupParticipantsOfTournament(ctx context.Context, tournamentID ids.TournamentID) ([]ListGroupParticipantsOfTournamentRow, error) {
	rows, err := q.db.Query(ctx, listGroupParticipantsOfTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupParticipantsOfTournamentRow{}
	for rows.Next() {
		var i ListGroupParticipantsOfTournamentRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ParticipantID,
			&i.Seed,
			&i.Lot,
			&i.Advanced,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, tournament_id, stage_id, position, status FROM groups WHERE tournament_id = $1 ORDER BY position
`

func (q *Queries) ListGroups(ctx context.Context, tournamentID ids.TournamentID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.Position,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsOfStage = `-- name: ListGroupsOfStage :many
SELECT id, tournament_id, stage_id, position, status FROM groups WHERE stage_id = $1 ORDER BY position
`

func (q *Queries) ListGroupsOfStage(ctx context.Context, stageID ids.StageID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsOfStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.StageID,
			&i.Position,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStages = `-- name: ListStages :many
SELECT id, tournament_id, position, format, group_count, advancement, best_of, bouts, swiss_rounds, result_deadline_seconds, status FROM stages WHERE tournament_id = $1 ORDER BY position
`

func (q *Queries) ListStages(ctx context.Context, tournamentID ids.TournamentID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStages, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Position,
			&i.Format,
			&i.GroupCount,
			&i.Advancement,
			&i.BestOf,
			&i.Bouts,
			&i.SwissRounds,
			&i.ResultDeadlineSeconds,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesOfTournaments = `-- name: ListStagesOfTournaments :many
SELECT id, tournament_id, position, format, group_count, advancement, best_of, bouts, swiss_rounds, result_deadline_seconds, status FROM stages WHERE tournament_id = ANY($1::uuid[]) ORDER BY tournament_id, position
`

func (q *Queries) ListStagesOfTournaments(ctx context.Context, tournamentIds []uuid.UUID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesOfTournaments, tournamentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Position,
			&i.Format,
			&i.GroupCount,
			&i.Advancement,
			&i.BestOf,
			&i.Bouts,
			&i.SwissRounds,
			&i.ResultDeadlineSeconds,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdvanced = `-- name: MarkAdvanced :exec
UPDATE group_participants SET advanced = true WHERE group_id = $1 AND participant_id = $2
`

type MarkAdvancedParams struct {
	GroupID       ids.GroupID
	ParticipantID ids.ParticipantID
}

func (q *Queries) MarkAdvanced(ctx context.Context, arg MarkAdvancedParams) error {
	_, err := q.db.Exec(ctx, markAdvanced, arg.GroupID, arg.ParticipantID)
	return err
}

const setGroupStatus = `-- name: SetGroupStatus :exec
UPDATE groups SET status = $2 WHERE id = $1
`

type SetGroupStatusParams struct {
	ID     ids.GroupID
	Status lifecycle.StageStatus
}

func (q *Queries) SetGroupStatus(ctx context.Context, arg SetGroupStatusParams) error {
	_, err := q.db.Exec(ctx, setGroupStatus, arg.ID, arg.Status)
	return err
}

const setStageStatus = `-- name: SetStageStatus :exec
UPDATE stages SET status = $2 WHERE id = $1
`

type SetStageStatusParams struct {
	ID     ids.StageID
	Status lifecycle.StageStatus
}

func (q *Queries) SetStageStatus(ctx context.Context, arg SetStageStatusParams) error {
	_, err := q.db.Exec(ctx, setStageStatus, arg.ID, arg.Status)
	return err
}
