// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournaments.sql

package db

import (
	"context"
	"time"

	"github.com/couchpartygames/opentournament/internal/ids"
	"github.com/couchpartygames/opentournament/internal/lifecycle"
	"github.com/google/uuid"
)

const completeTournament = `-- name: CompleteTournament :exec
UPDATE tournaments SET status = 'completed', updated_at = $2, completed_at = $2 WHERE id = $1
`

type CompleteTournamentParams struct {
	ID        ids.TournamentID
	UpdatedAt time.Time
}

func (q *Queries) CompleteTournament(ctx context.Context, arg CompleteTournamentParams) error {
	_, err := q.db.Exec(ctx, completeTournament, arg.ID, arg.UpdatedAt)
	return err
}

const deleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournaments WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id ids.TournamentID) error {
	_, err := q.db.Exec(ctx, deleteTournament, id)
	return err
}

const getDeclaredTournament = `-- name: GetDeclaredTournament :one
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments WHERE manifest = $1::text
`

func (q *Queries) GetDeclaredTournament(ctx context.Context, manifest string) (Tournament, error) {
	row := q.db.QueryRow(ctx, getDeclaredTournament, manifest)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Organizer,
		&i.Status,
		&i.StartsAt,
		&i.RegistrationOpensAt,
		&i.Capacity,
		&i.MinimumParticipants,
		&i.CheckInEnabled,
		&i.CheckInSeconds,
		&i.LastEventSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Manifest,
	)
	return i, err
}

const getTournament = `-- name: GetTournament :one
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments WHERE id = $1
`

func (q *Queries) GetTournament(ctx context.Context, id ids.TournamentID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Organizer,
		&i.Status,
		&i.StartsAt,
		&i.RegistrationOpensAt,
		&i.Capacity,
		&i.MinimumParticipants,
		&i.CheckInEnabled,
		&i.CheckInSeconds,
		&i.LastEventSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Manifest,
	)
	return i, err
}

const insertTournament = `-- name: InsertTournament :exec
INSERT INTO tournaments (id, game_id, name, organizer, status, starts_at, registration_opens_at,
                         capacity, minimum_participants, check_in_enabled, check_in_seconds,
                         created_at, updated_at, manifest)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12, $13)
`

type InsertTournamentParams struct {
	ID                  ids.TournamentID
	GameID              string
	Name                string
	Organizer           string
	Status              lifecycle.TournamentStatus
	StartsAt            time.Time
	RegistrationOpensAt time.Time
	Capacity            int32
	MinimumParticipants int32
	CheckInEnabled      bool
	CheckInSeconds      int32
	CreatedAt           time.Time
	Manifest            *string
}

func (q *Queries) InsertTournament(ctx context.Context, arg InsertTournamentParams) error {
	_, err := q.db.Exec(ctx, insertTournament,
		arg.ID,
		arg.GameID,
		arg.Name,
		arg.Organizer,
		arg.Status,
		arg.StartsAt,
		arg.RegistrationOpensAt,
		arg.Capacity,
		arg.MinimumParticipants,
		arg.CheckInEnabled,
		arg.CheckInSeconds,
		arg.CreatedAt,
		arg.Manifest,
	)
	return err
}

const listDeclaredTournaments = `-- name: ListDeclaredTournaments :many
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments
WHERE split_part(manifest, '/', 1) = ANY($1::text[])
  AND split_part(manifest, '/', 2) = ANY($2::text[])
ORDER BY id
`

type ListDeclaredTournamentsParams struct {
	Kinds      []string
	Namespaces []string
}

// kinds are the first segments of the manifests, such as tournament for
// tournament/<namespace>/<name> or recurring for an Occurrence.
func (q *Queries) ListDeclaredTournaments(ctx context.Context, arg ListDeclaredTournamentsParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listDeclaredTournaments, arg.Kinds, arg.Namespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Organizer,
			&i.Status,
			&i.StartsAt,
			&i.RegistrationOpensAt,
			&i.Capacity,
			&i.MinimumParticipants,
			&i.CheckInEnabled,
			&i.CheckInSeconds,
			&i.LastEventSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrenceTournaments = `-- name: ListOccurrenceTournaments :many
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments
WHERE starts_with(manifest, $1::text)
ORDER BY starts_at, id
`

// The Tournaments one Recurring Tournament declared, by the prefix
// recurring/<namespace>/<name>/ of their Occurrences.
func (q *Queries) ListOccurrenceTournaments(ctx context.Context, prefix string) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listOccurrenceTournaments, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Organizer,
			&i.Status,
			&i.StartsAt,
			&i.RegistrationOpensAt,
			&i.Capacity,
			&i.MinimumParticipants,
			&i.CheckInEnabled,
			&i.CheckInSeconds,
			&i.LastEventSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments
WHERE (status = $1 OR $1 = '')
  AND ($2::text IS NULL OR game_id = $2)
ORDER BY starts_at DESC, id
LIMIT $4 OFFSET $3
`

type ListTournamentsParams struct {
	Status     lifecycle.TournamentStatus
	GameID     *string
	Skip       int32
	MaxResults int32
}

// An empty status lists Tournaments in every status. Comparing with the
// status column first types the parameter as a TournamentStatus.
func (q *Queries) ListTournaments(ctx context.Context, arg ListTournamentsParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournaments,
		arg.Status,
		arg.GameID,
		arg.Skip,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Organizer,
			&i.Status,
			&i.StartsAt,
			&i.RegistrationOpensAt,
			&i.Capacity,
			&i.MinimumParticipants,
			&i.CheckInEnabled,
			&i.CheckInSeconds,
			&i.LastEventSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTournament = `-- name: LockTournament :one
SELECT id, game_id, name, organizer, status, starts_at, registration_opens_at, capacity, minimum_participants, check_in_enabled, check_in_seconds, last_event_seq, created_at, updated_at, completed_at, manifest FROM tournaments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTournament(ctx context.Context, id ids.TournamentID) (Tournament, error) {
	row := q.db.QueryRow(ctx, lockTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Organizer,
		&i.Status,
		&i.StartsAt,
		&i.RegistrationOpensAt,
		&i.Capacity,
		&i.MinimumParticipants,
		&i.CheckInEnabled,
		&i.CheckInSeconds,
		&i.LastEventSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Manifest,
	)
	return i, err
}

const nextEventSeq = `-- name: NextEventSeq :one
UPDATE tournaments SET last_event_seq = last_event_seq + 1 WHERE id = $1 RETURNING last_event_seq
`

func (q *Queries) NextEventSeq(ctx context.Context, id ids.TournamentID) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventSeq, id)
	var last_event_seq int64
	err := row.Scan(&last_event_seq)
	return last_event_seq, err
}

const registrationCounts = `-- name: RegistrationCounts :many
SELECT tournament_id,
       count(*) FILTER (WHERE status <> 'not-checked-in')::int AS registered,
       count(*) FILTER (WHERE checked_in_at IS NOT NULL)::int AS checked_in
FROM participants
WHERE tournament_id = ANY($1::uuid[])
GROUP BY tournament_id
`

type RegistrationCountsRow struct {
	TournamentID ids.TournamentID
	Registered   int32
	CheckedIn    int32
}

func (q *Queries) RegistrationCounts(ctx context.Context, tournamentIds []uuid.UUID) ([]RegistrationCountsRow, error) {
	rows, err := q.db.Query(ctx, registrationCounts, tournamentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationCountsRow{}
	for rows.Next() {
		var i RegistrationCountsRow
		if err := rows.Scan(&i.TournamentID, &i.Registered, &i.CheckedIn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTournamentStatus = `-- name: SetTournamentStatus :exec
UPDATE tournaments SET status = $2, updated_at = $3 WHERE id = $1
`

type SetTournamentStatusParams struct {
	ID        ids.TournamentID
	Status    lifecycle.TournamentStatus
	UpdatedAt time.Time
}

func (q *Queries) SetTournamentStatus(ctx context.Context, arg SetTournamentStatusParams) error {
	_, err := q.db.Exec(ctx, setTournamentStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateTournamentSettings = `-- name: UpdateTournamentSettings :exec
UPDATE tournaments
SET name = $2, starts_at = $3, registration_opens_at = $4, capacity = $5,
    minimum_participants = $6, check_in_enabled = $7, check_in_seconds = $8, updated_at = $9
WHERE id = $1
`

type UpdateTournamentSettingsParams struct {
	ID                  ids.TournamentID
	Name                string
	StartsAt            time.Time
	RegistrationOpensAt time.Time
	Capacity            int32
	MinimumParticipants int32
	CheckInEnabled      bool
	CheckInSeconds      int32
	UpdatedAt           time.Time
}

func (q *Queries) UpdateTournamentSettings(ctx context.Context, arg UpdateTournamentSettingsParams) error {
	_, err := q.db.Exec(ctx, updateTournamentSettings,
		arg.ID,
		arg.Name,
		arg.StartsAt,
		arg.RegistrationOpensAt,
		arg.Capacity,
		arg.MinimumParticipants,
		arg.CheckInEnabled,
		arg.CheckInSeconds,
		arg.UpdatedAt,
	)
	return err
}
