# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: OpenTournament Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: ./tests/OpenTournament.Tests.Unit
      run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore --configuration Release
    - name: Test
      working-directory: ./tests/OpenTournament.Tests.Unit
      run: dotnet test --no-restore --no-build --configuration Release --verbosity normal
