name: Publish to GitHub Container Registry

on:
  # trigger manual workflow
  workflow_dispatch:
  # trigger workflow on push to master when changes happen in one folder
  push:
    tags:
      - '*'
    #branches:
    #  - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: tagname
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.5.0
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish and push the container image
        working-directory: ./src/
        run: |
          dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=github '/p:ContainerImageTags="latest;${{ steps.tagname.outputs.tag }}"'